
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { UserProvider } from "@/context/UserContext";
import AuthLayoutWrapper from "@/components/AuthLayoutWrapper";
import { PreferencesProvider } from "@/context/PreferencesContext";
import LenisProvider from "@/components/LenisProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LenisProvider>
          <PreferencesProvider>
            <UserProvider>
              <AuthLayoutWrapper>{children}</AuthLayoutWrapper>
            </UserProvider>
          </PreferencesProvider>
        </LenisProvider>
      </body>
    </html>
  );
}